libgdiplus: fix-up libgdiplus.pc
as otherwise under Krogoth we fail a Q/A sanity check

ERROR: libgdiplus-2.10.8-r0 do_populate_sysroot: QA Issue: libgdiplus.pc failed sanity test (tmpdir) in path /data_drive/monotest/poky.krogoth/build/tmp/work/i586-poky-linux/libgdiplus/2.10.8-r0/sysroot-destdir/usr/lib/pkgconfig [pkgconfig]
ERROR: libgdiplus-2.10.8-r0 do_populate_sysroot: QA staging was broken by the package built above
ERROR: libgdiplus-2.10.8-r0 do_populate_sysroot: Function failed: do_qa_staging

Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>
(cherry picked from commit 177b285d390d4a57e0d1581f56d288c25f4ce592)
(backported from origin/master into krogoth based branch)